compilers:
  - compiler:
      spec: clang@15.0.0
      paths:
          #cc: cc
          #cxx: CC
          #f77: ftn
          #fc: ftn
        cc: /opt/rocm-5.4.0/llvm/bin/amdclang
        cxx: /opt/rocm-5.4.0/llvm/bin/amdclang++
        f77: /opt/rocm-5.4.0/llvm/bin/amdflang
        fc: /opt/rocm-5.4.0/llvm/bin/amdflang
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-amd/8.3.3
      - amd/5.4.0
      - libfabric
      - craype-x86-trento
      extra_rpaths: []
      environment:
        prepend_path:
          PKG_CONFIG_PATH: /opt/cray/xpmem/2.5.2-2.4_3.30__gd0f7936.shasta/lib64/pkgconfig
