packages:
  cray-mpich:
    require: "@8.1.23"
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.23%clang@15.0.0"
        prefix: /opt/cray/pe/mpich/8.1.23/ofi/amd/5.0
        modules:
          - cray-mpich/8.1.23
          - craype-network-ofi
  rocprim:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocprim@5.4.0
        prefix: /opt/rocm-5.4.0/rocprim
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  rocrand:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocrand@5.4.0
        prefix: /opt/rocm-5.4.0/rocrand
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  rocthrust:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocthrust@5.4.0
        prefix: /opt/rocm-5.4.0/rocthrust
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  rocsparse:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocsparse@5.4.0
        prefix: /opt/rocm-5.4.0/rocsparse
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  rocfft:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocfft@5.4.0
        prefix: /opt/rocm-5.4.0/rocfft
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  roctracer-dev:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: roctracer-dev@5.4.0
        prefix: /opt/rocm-5.4.0/roctracer
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  rocblas:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocblas@5.4.0
        prefix: /opt/rocm-5.4.0/rocblas
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  rocminfo:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: rocminfo@5.4.0
        prefix: /opt/rocm-5.4.0/rocminfo
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hipblas:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hipblas@5.4.0
        prefix: /opt/rocm-5.4.0/hipblas
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hipcub:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hipcub@5.4.0
        prefix: /opt/rocm-5.4.0/hipcub
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hipfft:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hipfft@5.4.0
        prefix: /opt/rocm-5.4.0/hipfft
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hiprand:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hiprand@5.4.0
        prefix: /opt/rocm-5.4.0/hiprand
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hipsolver:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hipsolver@5.4.0
        prefix: /opt/rocm-5.4.0/hipsolver
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hipsparse:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hipsparse@5.4.0
        prefix: /opt/rocm-5.4.0/hipsparse
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  miopen-hip:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: miopen-hip@5.4.0
        prefix: /opt/rocm-5.4.0/miopen
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hip:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hip@5.4.0
        prefix: /opt/rocm-5.4.0
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  hsa-rocr-dev:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: hsa-rocr-dev@5.4.0
        prefix: /opt/rocm-5.4.0/hsa
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  llvm-amdgpu:
    require: "@5.4.0"
    buildable: false
    externals:
      - spec: llvm-amdgpu@5.4.0
        prefix: /opt/rocm-5.4.0/llvm
        modules:
          - amd/5.4.0
          - craype-accel-amd-gfx90a
  cmake:
    require: "@3.23.2"
    buildable: false
    externals:
      - spec: cmake@3.23.2
        prefix: /sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd
        modules:
          - cmake/3.23.2
  perl:
    require: "@5.34.1"
    buildable: false
    externals:
      - spec: perl@5.34.1
        prefix: /sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/perl-5.34.0-2f4kqqwg4xkrrapb5peh5m6fw2cargdl
        modules:
          - perl/5.34.0
  openblas:
    require: "@0.3.17"
    buildable: false
    externals:
      - spec: openblas@0.3.17
        prefix: /sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/openblas-0.3.17-54x7v5e4i6yxqs6j5nebrbztpy4lftj4
        modules:
          - openblas/0.3.17
  umpire:
    require: "@6.0.0"
    buildable: false
    externals:
      - spec: umpire@6.0.0
        prefix: /sw/frontier/spack-envs/base/opt/cray-sles15-zen3/clang-15.0.0-rocm5.3.0/umpire-6.0.0-4h6ox6p5o4zj6zhzgnly7a3b56jyghrz
        modules:
          - umpire/6.0.0
  trilinos:
    require:
      - any_of: ["@13.4.0.2023.02.28", "@develop"]
  nalu-wind:
    variants: ~trilinos-solvers
  libffi:
    require: "@3.4.2"
  all:
    compiler:
      - clang@15.0.0
    providers:
      mpi: [cray-mpich@8.1.23]
      blas: [openblas]
      lapack: [openblas]
    variants: build_type=Release amdgpu_target=gfx90a
