packages:
  cray-mpich:
    require: "@8.1.17"
    buildable: false
    externals:
      - spec: "cray-mpich@8.1.17%clang@14.0.0"
        prefix: /opt/cray/pe/mpich/8.1.17/ofi/amd/5.0
        modules:
          - cray-mpich/8.1.17
          - craype-network-ofi
# python:
#   require: "@3.9.12.1"
#   buildable: false
#   externals:
##    - spec: "python@3.9.12.1%clang@14.0.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-sles15-zen3"
#     - spec: "python@3.9.12.1%clang@14.0.0"
#       prefix: /opt/cray/pe/python/3.9.12.1
#       modules:
#         - cray-python/3.9.12.1
  rocprim:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocprim@5.2.0
        prefix: /opt/rocm-5.2.0/rocprim
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocrand:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocrand@5.2.0
        prefix: /opt/rocm-5.2.0/rocrand
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocthrust:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocthrust@5.2.0
        prefix: /opt/rocm-5.2.0/rocthrust
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocsparse:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocsparse@5.2.0
        prefix: /opt/rocm-5.2.0/rocsparse
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hip:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hip@5.2.0
        prefix: /opt/rocm-5.2.0
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocfft:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocfft@5.2.0
        prefix: /opt/rocm-5.2.0/rocfft
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  roctracer-dev:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: roctracer-dev@5.2.0
        prefix: /opt/rocm-5.2.0/roctracer
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocblas:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocblas@5.2.0
        prefix: /opt/rocm-5.2.0/rocblas
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  rocminfo:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: rocminfo@5.2.0
        prefix: /opt/rocm-5.2.0/rocminfo
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hipblas:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hipblas@5.2.0
        prefix: /opt/rocm-5.2.0/hipblas
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hipcub:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hipcub@5.2.0
        prefix: /opt/rocm-5.2.0/hipcub
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hipfft:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hipfft@5.2.0
        prefix: /opt/rocm-5.2.0/hipfft
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hiprand:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hiprand@5.2.0
        prefix: /opt/rocm-5.2.0/hiprand
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hipsolver:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hipsolver@5.2.0
        prefix: /opt/rocm-5.2.0/hipsolver
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hipsparse:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hipsparse@5.2.0
        prefix: /opt/rocm-5.2.0/hipsparse
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  miopen-hip:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: miopen-hip@5.2.0
        prefix: /opt/rocm-5.2.0/miopen
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  hsa-rocr-dev:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: hsa-rocr-dev@5.2.0
        prefix: /opt/rocm-5.2.0/hsa
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  llvm-amdgpu:
    require: "@5.2.0"
    buildable: false
    externals:
      - spec: llvm-amdgpu@5.2.0
        prefix: /opt/rocm-5.2.0/llvm
        modules:
          - rocm/5.2.0
          - craype-accel-amd-gfx90a
  cmake:
    require: "@3.23.2"
    buildable: false
    externals:
      - spec: cmake@3.23.2
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd
        modules:
          - cmake/3.23.2
  perl:
    require: "@5.34.1"
    buildable: false
    externals:
      - spec: perl@5.34.1
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/perl-5.34.0-2f4kqqwg4xkrrapb5peh5m6fw2cargdl
        modules:
          - perl/5.34.0
  openblas:
    require: "@0.3.17"
    buildable: false
    externals:
      - spec: openblas@0.3.17
        prefix: /sw/crusher/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/openblas-0.3.17-54x7v5e4i6yxqs6j5nebrbztpy4lftj4
        modules:
          - openblas/0.3.17
  trilinos:
    require: "@develop"
  all:
    compiler:
      - clang@14.0.0
    providers:
      mpi: [cray-mpich@8.1.17]
      blas: [openblas]
      lapack: [openblas]
    variants: build_type=Release amdgpu_target=gfx90a
